### ISSUE TITLE
Mfa 

### ISSUE THREAD

**Issue by fkhera** [enode-engineering/tesla-oauth2#1]
Hi I am just trying to understand the flow from user. I use The owner api code everyday to control powerwall reserve levels.

I do not have Mfa enabled so I feel like for time being I should not and then use the code as is.
It seems now I may have to save this refresh token and use that and keep track of token expiry.
That becomes much more important once Mfa goes online and forced?

just to know the flow we only need Mfa to get our initial token then we need to save the other tokens and if we find our script ever malfunctions then we use Mfa token to get that refresh access token again?

Is that the right way to think about this problem ?

Also is there a way to enable and disable MFA in your Tesla account.

**Comment by heumn** [comment]
> Is that the right way to think about this problem ?

That sounds correct yeah :) 

> Also is there a way to enable and disable MFA in your Tesla account.

Yeah under account settings you can enable disable it :)

**Comment by fkhera** [comment]
Aww okay I disabled it for now.

Thank you so much for your help!  I think it will have to remain disabled a
while cause I run code everyday to change settings on my powerwalls.
I got your code working :) You are the best!
I will be curious if you get the MFA working.  Keep me posted.

**Comment by heumn** [comment]
We got 2FA working :) Updated the script

Glad I could help!

**Comment by fkhera89** [comment]
I noticed you added more retries I am using this for automation did you find sometimes the apis returned errors ?

**Comment by heumn** [comment]
There’s some attempts (I assume) on Tesla’s end to try to mitigate this
