### ISSUE TITLE
ValueError: Can't find device `Device #1`

### ISSUE THREAD

**Issue by chrispazz** [enode-engineering/tesla-oauth2#12]
Using user, password and passcode it answer with:

ValueError: Can't find device `Device #1`

Thanks

**Comment by Belokan** [comment]
Same issue here with MFA enable account.

**Comment by larsoeh** [comment]
I Solved the problem in the following way:
Remove the 2 lines:
-            device_name = f"Device #{args.device}"
-            devices = [f for f in factors if f["name"] == device_name]
Add the two lines instead (without the '+' signs:
+            device_id = args.device
+            devices = [f for f in factors if f["name"][-1] == device_id]

Best regards.

**Comment by MikeBishop** [comment]
Tesla apparently uses the name "Device #2" for the second device you add, even if you later remove the old one.
