### ISSUE TITLE
Failing at Step 2

### ISSUE THREAD

**Issue by GeorgeIoak** [enode-engineering/tesla-oauth2#2]
I'm running some tests and I'm a bit stuck. The first step passes as I get this response:
```
Get auth form success - 1 attempt(s).
```
but then I fail at the next step with this response:
```
ValueError: Didn't post auth form in 10 attempts.
```
I've confirmed that I get a `csrf` as well as a `transaction_id` but I can't sem to figure out why I'm not getting the authorization code

**Comment by benderl** [comment]
Should be fixed with #3

**Comment by GeorgeIoak** [comment]
I'll have to look at your PR but I literally just got it working for me. I haven't enabled MFA on my account yet so my rather ugly hack was:
```
for attempt in range(MAX_ATTEMPTS):
        resp = session.post(
            "https://auth.tesla.com/oauth2/v3/authorize", headers=headers, params=params, data=data, allow_redirects=False
        )
        print("\nThe 2nd response code is", resp.status_code, "\n")
        print("The 2nd response.text is:\n", resp.text, "\n")
        print("The 2nd response.headers is:\n", resp.headers, "\n")
        if resp.status_code == 302:
            if attempt == 0:
                code = parse_qs(resp.headers["Location"])["https://auth.tesla.com/void/callback?code"]
                print("Code -", code, "\n")
            else:
                code_challenge = parse_qs(resp.headers["Location"])["code_challenge"]
                print("Code_Challenge - ", code_challenge, "\n")
        if resp.ok and "<title>" in resp.text:
            print(f"Post auth form success - {attempt + 1} attempt(s).")
            break
        time.sleep(3)
    else:
        #GIraise ValueError(f"Didn't post auth form in {MAX_ATTEMPTS} attempts.")
        pass
```
What I saw was that you would get the `code` with the first post request and that `response_code` was 302. The next post returned a `response_code` of 200 and the js code. On the 3rd attempt you would get a `respond_code` of 302 again and the `code_challenge` would be in both the `resp.text' as well as in the `resp.headers` again.

When you go to the 3rd step you'll get the `access_token` and I read that it is valid for 45 days I think. I've only run the code a couple of times but the `access_token` has not changed for me so far.

**Comment by heumn** [comment]
@benderl fixed this in his PR :)
