### ISSUE TITLE
now hangs

### ISSUE THREAD

**Issue by lgkahn** [enode-engineering/tesla-oauth2#20]
was working now hanging.. any ideas.

**Comment by swm11** [comment]
I'm seeing the same problem.  It hangs in login() starting the initial session:
resp = session.get("https://auth.tesla.com/oauth2/v3/authorize", headers=headers, params=params)

**Comment by swm11** [comment]
I've created a pull request that simply sets:
  UA = ""
  X_TESLA_USER_AGENT = ""
in the Python version of the script.

This experimentally works and matches Timdoor's documentation here:
  https://tesla-api.timdorr.com/api-basics/authentication
Which says:
 "Avoid setting a User-Agent header that looks like a browser (such
  as Chrome or Safari). The SSO service has protections in place
  that will require executing JavaScript if a browser-like user
  agent is detected."

**Comment by heumn** [comment]
Thanks a lot for fixing this @swm11 :) Closing issue
