### ISSUE TITLE
Not working without MFA

### ISSUE THREAD

**Issue by mboremski** [enode-engineering/tesla-oauth2#6]
tried your code.
got back:
```
(venv) D:\git\tesla-oauth2>python tesla.py -e "my@ema.il" -p "myPassword"
Get auth form success - 5 attempt(s).
Post auth form success - 4 attempt(s).
Traceback (most recent call last):
  File "tesla.py", line 206, in <module>
    login(args.email, args.password)
  File "tesla.py", line 164, in login
    code = parse_qs(resp.headers["location"])["https://auth.tesla.com/void/callback?code"]
  File "D:\git\tesla-oauth2\venv\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

Must be something simple I think.

Using Python3.8

**Comment by heumn** [comment]
You can get blocked for too many attempts. Sure that’s not the case?

**Comment by mboremski** [comment]
> Sure that’s not the case?

I am sure.
Even the first run did bring up this error but with just one attempt.

For me it looks like a tabbing-problem in some way.
Sure there can be a for -> else?
https://github.com/enode-engineering/tesla-oauth2/blob/4799c957d8bdc5e983d7bfaaf48d80f3d5754044/tesla.py#L150-L162

**Comment by MrHobbes74** [comment]
I also get the same with my non-MFA account. After some debugging: there is no location in the header at step 3.....

**Comment by heumn** [comment]
I have tested this on both non and 2FA accounts. I need a bit more info about what is not working for you

**Comment by benderl** [comment]
> For me it looks like a tabbing-problem in some way.
> Sure there can be a for -> else?

Just to clarify this: https://book.pythontips.com/en/latest/for_-_else.html#else-clause
