### ISSUE TITLE
Don't utilize "Max Retries" on POST requests to minimize account lockouts.

### ISSUE THREAD

**Issue by corsair** [enode-engineering/tesla-oauth2#8]
### Problem
The current behavior for authenticating credentials risks causing an account lockout.

```python
for attempt in range(MAX_ATTEMPTS):
        resp = session.post(
            "https://auth.tesla.com/oauth2/v3/authorize", headers=headers, params=params, data=data, allow_redirects=False
        )
        if resp.ok and (resp.status_code == 302 or "<title>" in resp.text):
            print(f"Post auth form success - {attempt + 1} attempt(s).")
            break
        time.sleep(3)
    else:
        raise ValueError(f"Didn't post auth form in {MAX_ATTEMPTS} attempts.")
```

### Reason
If you've reached the POST request for authorizing an account and sending its credentials, this already guarantees that the current session has a valid cookie and won't risk encountering the "WAF" temporary block.

Thus, by attempting to authenticate an account multiple times (10, as default in the current code), this significantly risks causing a Tesla Account to lock out and requiring the individual to reset their password.

### Proposed Solution
Remove the attempts loop for authenticating and send a single request similar to the passcode.

**Comment by corsair** [comment]
Seems the [WAF can still trigger](https://github.com/timdorr/tesla-api/issues/260#issuecomment-772449678) sadly but still worthwhile to try to look for the "invalid credentials" status text and return back early if seen to avoid more attempts.

**Comment by heumn** [comment]
Will dig more into this

**Comment by heumn** [comment]
This has been improved :)
